# Generated by Django 5.2 on 2025-05-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Urgent'), (1, 'High'), (2, 'Normal'), (3, 'Low')], default=2),
        ),
    ]
